version: "2.4"

services:
  postgres:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /data
    volumes:
      - $PWD/docker/volumes/pg:/data
    ports:
      - "127.0.0.1:$POSTGRES_PORT:5432"
    restart: always

  redis:
    image: redis:3.2.11-alpine
    hostname: redis
    ports:
      - "127.0.0.1:$REDIS_PORT:6379"
    volumes:
      - $PWD/docker/volumes/redis:/data