version: "2.4"

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
    - "127.0.0.1:$RABBITMQ_PORT:5672"
    - "$RABBITMQ_ADMIN_PORT:15672"
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
      RABBITMQ_DEFAULT_VHOST: $RABBITMQ_VHOST
    volumes:
      - $PWD/docker/volumes/rabbitmq:/var/lib/rabbitmq

  db:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /data
    volumes:
      - $PWD/docker/volumes/pg:/data
    ports:
      - "127.0.0.1:$POSTGRES_PORT:5432"
    restart: always

  redis:
    image: redis:3.2.11-alpine
    hostname: redis
    ports:
      - "127.0.0.1:$REDIS_PORT:6379"
    volumes:
      - $PWD/docker/volumes/redis:/data