# FROM openresty/openresty:1.15.8.2-7-xenial-nosse42
FROM python:3.7-buster

ENV OMAHA_SERVER_PATH /srv/omaha
WORKDIR ${OMAHA_SERVER_PATH}

RUN wget -qO - https://openresty.org/package/pubkey.gpg | apt-key add -
RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
RUN apt-get update -y && apt-get -y install software-properties-common apt-transport-https
RUN add-apt-repository -y "deb http://openresty.org/package/debian $(lsb_release -sc) openresty"
RUN echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-6.x.list

RUN apt-get update -y \
    && apt-get install -y wget gnupg ca-certificates bash libfuse-dev libcurl4-openssl-dev libxml++2.6-dev libssl-dev rsyslog supervisor filebeat uwsgi-plugin-python3 nginx openresty luajit libnginx-mod-http-lua

ARG S3FS_VERSION=1.86
RUN \
  mkdir /usr/src/omaha-server \
  && wget -q https://github.com/s3fs-fuse/s3fs-fuse/archive/v${S3FS_VERSION}.tar.gz -O /usr/src/omaha-server/v${S3FS_VERSION}.tar.gz \
  && tar -xz -C /usr/src/omaha-server -f /usr/src/omaha-server/v${S3FS_VERSION}.tar.gz \
  && cd /usr/src/omaha-server/s3fs-fuse-${S3FS_VERSION} \
  && ./autogen.sh \
  && ./configure --prefix=/usr \
  && make \
  && make install \
  && mkdir -p /srv/omaha_s3 \
  && rm /usr/src/omaha-server/v${S3FS_VERSION}.tar.gz

# Setup application dependencies
RUN mkdir -p $OMAHA_SERVER_PATH/requirements
ADD Pipfile Pipfile.lock $OMAHA_SERVER_PATH/

RUN \
  pip install pipenv \
  && pipenv install --system --deploy
