FROM python:3.7-slim

WORKDIR /srv/omaha
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && apt-get install -qq apt-utils gnupg2 wget
RUN wget -qO - https://openresty.org/package/pubkey.gpg | apt-key add - \
  && wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
RUN echo "deb https://openresty.org/package/debian buster openresty" | tee -a /etc/apt/sources.list.d/openresty.list
RUN echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-6.x.list

RUN apt-get update -qq \
  && apt-get install -qq --no-install-recommends automake build-essential libmagic1 libmagic-dev libfuse-dev libcurl4-openssl-dev libxml++2.6-dev libssl-dev \
    rsyslog supervisor filebeat uwsgi-plugin-python3 nginx openresty luajit libnginx-mod-http-lua \
  && apt-get clean

ARG S3FS_VERSION=1.86
RUN \
  mkdir /usr/src/omaha-server \
  && wget -q https://github.com/s3fs-fuse/s3fs-fuse/archive/v${S3FS_VERSION}.tar.gz -O /usr/src/omaha-server/v${S3FS_VERSION}.tar.gz \
  && tar -xz -C /usr/src/omaha-server -f /usr/src/omaha-server/v${S3FS_VERSION}.tar.gz \
  && cd /usr/src/omaha-server/s3fs-fuse-${S3FS_VERSION} \
  && ./autogen.sh \
  && ./configure --prefix=/usr \
  && make \
  && make install \
  && mkdir -p /srv/omaha_s3 \
  && rm /usr/src/omaha-server/v${S3FS_VERSION}.tar.gz

RUN mkdir -p /srv/omaha/requirements
ADD Pipfile Pipfile.lock /srv/omaha/

RUN \
  pip install pipenv \
  && pipenv install --system --deploy
