version: '3.7'

services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  redis:
    image: redis:3.2.6-alpine

  web:
    privileged: true
    ports:
      - '9090:80'
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    links:
      - db
      - redis
    environment:
      HOST_NAME: $HOST_NAME
      DB_HOST: db
      DB_USER: $POSTGRES_USER
      DB_NAME: $POSTGRES_DB
      DB_PASSWORD: $POSTGRES_PASSWORD
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: 'omaha_server.settings'
      AWS_STORAGE_BUCKET_NAME: $AWS_STORAGE_BUCKET_NAME
      AWS_ROLE: $AWS_ROLE
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    sysctls:
      net.core.somaxconn: 1024
