# Generated by Django 2.2 on 2020-04-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0034_auto_20190409_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='file_hash_sha256',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Hash SHA256'),
        ),
    ]
